import mysql.connector
try : 
    conn = mysql.connector.connect(
        user = "root",
        password = "mysql2610",
        host = "localhost",
        port = 3306,
        database = "pdbc"
    )
    if conn.is_connected():
        print("Successfully Connected")
except : 
    print("Connection failed")

## fetchall() - used to fetch all data generated by SELECT query 
## returns a list of tuples , each tuple represents a row 

cur = conn.cursor()
sql = "SELECT * FROM tutorial;"
## NO commit required because data is not changed just fetched 
cur.execute(sql)
data = cur.fetchall()
for i in data:
    print(list(i))
print(f"{len(data)} : rows fetched")
## we can iterate multiple times 
# for i in data:
#     print(list(data))
    
cur.close()
conn.close()